### ISSUE TITLE
Dev Talk

### ISSUE THREAD

**Issue by CosmicWebServices** [bridgevar/bridgevar-js#11]

**Comment by CosmicWebServices** [comment]
anyone on?

**Comment by joker314** [comment]
heya. So, was the merge smooth?

**Comment by CosmicWebServices** [comment]
Yes

**Comment by CosmicWebServices** [comment]
Very smooth like wood that was just sanded

**Comment by CosmicWebServices** [comment]
What are we doing now?

**Comment by joker314** [comment]
We appear to be making small-talk (programming reference intended a bit)

**Comment by CosmicWebServices** [comment]
No future plans

**Comment by joker314** [comment]
Well, we need to synchronise with my PR

**Comment by CosmicWebServices** [comment]
Oh yeah

**Comment by joker314** [comment]
I'll put it here to stop it from getting lost:

```
var Scratch = require('scratch-api');
var bridgeUsers = require('./users.json');
const statusId = 115628457;
const serverNo = 1; //0 based indexing plz
const serverId = '☁ server' + serverNo + 'timestamp'
const username = 'bridgevar';
var password = 'password';
var calculateVars = function(){
    var orders = bridgeUsers.length;
    var start = Math.ceil(orders/servers) * serverNo;
    var end = Math.ceil(orders/servers) * (serverNo + 1);
}
var createBridges = function(start, end) {
    for (var i=start; i<end; i++) {
        var firstProjectId = bridgeUsers.users[i].firstProjectId;
        var secondProjectId = bridgeUsers.users[i].secondProjectId;
        var firstName = bridgeUsers.users[i].firstName;
        var secondName = bridgeUsers.users[i].secondName;
        var myi = i;
        user.cloudSession(firstProjectId, function(err, firstcloud) {
            user.cloudSession(secondProjectId, function(err, secondcloud) {
                firstcloud.on('set', function(name, value) {
                    if (name === '☁ ' + firstName) {
                        secondcloud.set('☁ ' + secondName, value);
                    }
                });
                secondcloud.on('set', function(name, value) {
                    if (name === '☁ ' + secondName) {
                        firstcloud.set('☁ ' + secondName, value);
                    }
                });
            });
        });
    }

}
Scratch.UserSession.create(username, password, function(err, user) {
    user.cloudSession(statusId, function(err, statusSession) {
        var pulse = function(session) {session.set(serverId, Date.now()); setTimeout(pulse, 50000, session)};
        pulse(statusSession);
    });
});
```

**Comment by CosmicWebServices** [comment]
OK

**Comment by CosmicWebServices** [comment]
HI

**Comment by joker314** [comment]
Hi

**Comment by joker314** [comment]
Would you like to help out on one of my projects since we are sorta inactive?

**Comment by CosmicWebServices** [comment]
Sure

**Comment by joker314** [comment]
https://github.com/joker314/ServerSynchronisation

Basically our thing but it is a server-side database on Scratch

**Comment by joker314** [comment]
I'll make an issue for us to talk

**Comment by CosmicWebServices** [comment]
OK

**Comment by ghost** [comment]
did the ST write back?

**Comment by joker314** [comment]
Not yet. They said they check mail daily but might take a few days to respond

**Comment by ghost** [comment]
:(

**Comment by joker314** [comment]
Anybody on? I'd like to do a multi-user test again

**Comment by ghost** [comment]
k

**Comment by ghost** [comment]
on

**Comment by joker314** [comment]
So, what are our plans. Shall we not distribute computing but instead have as many servers testing for availability eery minute, but one server active? Just as a test?

**Comment by ghost** [comment]
@joker314 maybe as a test

**Comment by ghost** [comment]
but only a test

**Comment by haylinmoore** [comment]
hey. How would I correctly fill out the users.json for multiple projects?

**Comment by CosmicWebServices** [comment]
Hi @herohamp currently you would do @bwbw223 correct me if I am wrong: `{
"users": [{"firstProjectId": <insert id>, "secondProjectId": <insert id>, "firstName": "<insert var>r", "secondName": "<insert var>"}],[{"firstProjectId": <insert id>, "secondProjectId": <insert id>, "firstName": "<insert var>", "secondName": "<insert var>"}]
}`

**Comment by ghost** [comment]
@herohamp `"users"` is an array containing bridge objects.  Each bridge object contains a `"firstProjectId"`, `"secondProjectId"` a `"firstName"` and a `secondName`  the project ids are just the project Id, like `scratch.mit.edu/projects/<projectId>`   the firstname and secondname are the names of the cloud variables that are going to be bridged

**Comment by haylinmoore** [comment]
ok thanks

**Comment by CosmicWebServices** [comment]
@joker314, @bwbw223 and I changed A LOT so check it out!
Edited by @bwbw223 for grammar

**Comment by haylinmoore** [comment]
can the latests users.json be out on GH?

**Comment by CosmicWebServices** [comment]
that is the latest and yea

**Comment by haylinmoore** [comment]
So nobody has make a bridge?

**Comment by haylinmoore** [comment]
Bridgevar color scheme?

**Comment by ghost** [comment]
@herohamp we are really deploying the service early next month, right now, the code is in development

**Comment by haylinmoore** [comment]
ok

**Comment by CosmicWebServices** [comment]
I think we are going back to gitter so I will close this as of now
