### ISSUE TITLE
ogginglay nlyoay ogslay taay reationcay foay ridgesbay

### ISSUE THREAD

**Issue by ghost** [bridgevar/bridgevar-js#13]
saay erpay itletay

**Comment by CosmicWebServices** [comment]
???

**Comment by ghost** [comment]
Igpay atinlay.

**Comment by ghost** [comment]
Pig latin.

**Comment by ghost** [comment]
logging only logs at creation of bridges

**Comment by CosmicWebServices** [comment]
Yeah I noticed that did u see my issue?

**Comment by CosmicWebServices** [comment]
Will u fix it or will I?

**Comment by CosmicWebServices** [comment]
I can fix this one and you can fix the bridge problem

**Comment by ghost** [comment]
I will fix the bridge one.

**Comment by CosmicWebServices** [comment]
OK

**Comment by CosmicWebServices** [comment]
I will make a pr after I am done my chore

**Comment by CosmicWebServices** [comment]
@bwbw223 I just realised if we work on the bugs at the same time there will be conflicts

**Comment by ghost** [comment]
yeah you go first

**Comment by CosmicWebServices** [comment]
OK (in the mean time figure out how to fix yours)

**Comment by CosmicWebServices** [comment]
testing my fix now

**Comment by CosmicWebServices** [comment]
It works! making a pr

**Comment by CosmicWebServices** [comment]
OK it is merged! @bwbw223 your turn!
