### ISSUE TITLE
Bridge not working?

### ISSUE THREAD

**Issue by CosmicWebServices** [bridgevar/bridgevar-js#14]
https://scratch.mit.edu/projects/115557663/ is sending to https://scratch.mit.edu/projects/115557644/ but not the other way?

**Comment by CosmicWebServices** [comment]
@bwbw223 are you working on this now?

**Comment by ghost** [comment]
yaasss

**Comment by CosmicWebServices** [comment]
Yay my fix was easy thankfully!

**Comment by ghost** [comment]
Its running can you test it via the projects?

**Comment by CosmicWebServices** [comment]
OK I will

**Comment by CosmicWebServices** [comment]
It works!

**Comment by CosmicWebServices** [comment]
@bwbw223

**Comment by ghost** [comment]
Yassss

**Comment by CosmicWebServices** [comment]
OK make a pr and we will merge! if no conflicts

**Comment by CosmicWebServices** [comment]
:P

**Comment by CosmicWebServices** [comment]
@bwbw223

**Comment by CosmicWebServices** [comment]
...

**Comment by CosmicWebServices** [comment]
Also when you merge I found out how you can simplify my code

**Comment by ghost** [comment]
I just commmitted it to master

**Comment by CosmicWebServices** [comment]
Cool

**Comment by CosmicWebServices** [comment]
@bwbw223 #16
