### ISSUE TITLE
ddaay aay icenselay

### ISSUE THREAD

**Issue by ghost** [bridgevar/bridgevar-js#17]
saay erpay itletay

**Comment by CosmicWebServices** [comment]
MIT

**Comment by ghost** [comment]
ye be clever with yer pick of ye license

**Comment by CosmicWebServices** [comment]
do you have another suggestion?

**Comment by ghost** [comment]
I think the mit makes sense.

**Comment by CosmicWebServices** [comment]
OK

**Comment by CosmicWebServices** [comment]
I am working on another project https://github.com/ilovecode1/Phosphorus-Plus-2.0/

**Comment by joker314** [comment]
mit is good
or public domain?

**Comment by ghost** [comment]
@joker314 I'd pprefer to reserve _some_ rights

**Comment by CosmicWebServices** [comment]
I agree with @bwbw223

**Comment by CosmicWebServices** [comment]
I merged
