### ISSUE TITLE
Website 

### ISSUE THREAD

**Issue by haylinmoore** [bridgevar/bridgevar-js#18]
I could make a website that shows all the bridges and allows you to create bridges. If you guys want I can make that for you guys

**Comment by CosmicWebServices** [comment]
That would be cool @bwbw223 and @joker314 what do you think?

**Comment by haylinmoore** [comment]
It would be in nodeJS if that is ok with you guys

**Comment by ghost** [comment]
Hmmm...  Maybe we can just make a gh-pages branch with the site and embed a google form?

**Comment by haylinmoore** [comment]
Hmmm what do you guys run this off of ATM

**Comment by ghost** [comment]
node.  The software was built so we each run run the script on our devices and it automatically divides the work.

**Comment by CosmicWebServices** [comment]
hi

**Comment by CosmicWebServices** [comment]
@herohamp do you want me to add you to this org?

**Comment by ghost** [comment]
@CosmicWebServices just wait a minute.

**Comment by CosmicWebServices** [comment]
OK

**Comment by ghost** [comment]
since he's (from what I know) just making a site, maybe add him with read only access (so he's a member but can only make issues and PR)

**Comment by CosmicWebServices** [comment]
Oh OK

**Comment by herohamp** [comment]
Wait what do you haves have running the node? Someone's pi? A VPS?

**Comment by ghost** [comment]
(a pi), a (pi2 or a 8-core server) and (a laptop)

**Comment by haylinmoore** [comment]
https://bridgevar.github.io I will work on website when I have time. I am on vacation ATM.

**Comment by ghost** [comment]
great!

**Comment by CosmicWebServices** [comment]
@herohamp did u see that I invited u

**Comment by ghost** [comment]
yes he did

**Comment by haylinmoore** [comment]
Yeah I made a repo :P

**Comment by CosmicWebServices** [comment]
noice

**Comment by haylinmoore** [comment]
Will there be one central server running bridge?

**Comment by haylinmoore** [comment]
Because if so I could write a nodeJS webpage for it that would use the users.json to show what projects have current connections

**Comment by CosmicWebServices** [comment]
There are 3 but we have a project that will switch which one is the main

**Comment by haylinmoore** [comment]
Does anyone have gitter? That would make this so much easier

**Comment by CosmicWebServices** [comment]
we do

**Comment by CosmicWebServices** [comment]
it is on the ready

**Comment by CosmicWebServices** [comment]
readme

**Comment by CosmicWebServices** [comment]
@herohamp https://gitter.im/bridgevar/bridgevar-js?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by joker314** [comment]
Um, ok

**Comment by CosmicWebServices** [comment]
ignore

**Comment by joker314** [comment]
shall we add a sign saying if the server is active?

**Comment by CosmicWebServices** [comment]
ya

**Comment by haylinmoore** [comment]
Ok. I have an idea on how. though it involves a tiny nodeJS server

**Comment by joker314** [comment]
@herohamp 
Lucily, our servers already pulse a message to a Scratch project when they are active.
Taking advantage of the varserver and crossorigin.me  have implemented it, buut Scratch sometimes gives me a 502 which is really annoying. If it gives anything but a 200 it curretly says `Failed to get server status. Try`[reloading](./)`the page?`. If you would like to jag up the swag in the CSS and stuff-- feel free! :)

**Comment by CosmicWebServices** [comment]
I think I will close this as of now.
