### ISSUE TITLE
Bridgevar API for scratch

### ISSUE THREAD

**Issue by CosmicWebServices** [bridgevar/bridgevar-js#20]
We need to make custom blocks/nodejs code that will let the users of our service interact with the bridgevars because they may not want new info from the other project at certain times or not send info at certain times. I know there are already ways to do this but a way to do this easier

**Comment by joker314** [comment]
So baically a way to send a signal to our server to stop/start listening? This could be achieved through a backpackable sprite

**Comment by CosmicWebServices** [comment]
Yep

**Comment by CosmicWebServices** [comment]
But in different ways because they may want to send but not receive, receive but not send, not send at all...

**Comment by joker314** [comment]
Ok, well we could have a Cloud Var names `bridgeVar` that they create, and they can use our backpackede sprite to set it to different numbers:
0: No send no receive (service off even for streaming)
1: Send but no recieve
2: Recieve but no end
3: Operate service normally
join(4)(timestamp): Reset to 3 when the timestamp occurs

**Comment by CosmicWebServices** [comment]
Nice

**Comment by joker314** [comment]
This should be quite simpe once we add this to our server''s coding. Do you thin you can mae a sprite for them to backpack or shall I (it should act on broadcasts)

**Comment by CosmicWebServices** [comment]
So how easy would this be (did we fix the bug?)

**Comment by CosmicWebServices** [comment]
I will make a sprite

**Comment by joker314** [comment]
1) No we didn't fix the bug but I referenced an issue the LogFather Made that may explain it

2) Ok

**Comment by CosmicWebServices** [comment]
Oh

**Comment by joker314** [comment]
ok

**Comment by CosmicWebServices** [comment]
Working on the sprite (will take a second basically)

**Comment by CosmicWebServices** [comment]
https://scratch.mit.edu/projects/116422317/

**Comment by joker314** [comment]
Nice! Shall we do a NUMBER + 4 to signify you are checking if a server is active, an if there is an active server it would respond by taking away 4?

Like if you wanted to test if there is a server active and you have status 3, you would set it to 7. The server takes everything mod 4 so it wouldn't care, but it would check that it is greater than 3 and respond by taking away 4

**Comment by CosmicWebServices** [comment]
Is that for making the server active and it will do 7 instead of setting it to 3 and it will wait until it equals 3 or else the server is off?

**Comment by joker314** [comment]
Yup
Make it wait 5 seconds or until it is true

**Comment by joker314** [comment]
Or maybe it should keep it at 7 until a server joins and fixes it

**Comment by CosmicWebServices** [comment]
Im back

**Comment by CosmicWebServices** [comment]
Done the API

**Comment by CosmicWebServices** [comment]
Oh we still need to make the API work in the code

**Comment by joker314** [comment]
yup gtg

**Comment by ghost** [comment]
Where is thelogfathers issue?

**Comment by CosmicWebServices** [comment]
The one he made?

**Comment by ghost** [comment]
nm

**Comment by CosmicWebServices** [comment]
K

**Comment by CosmicWebServices** [comment]
#26

**Comment by ghost** [comment]
I don't really feel that this is necessary...  I mean, this can easily be workarounded with one extra CV

**Comment by CosmicWebServices** [comment]
I will close this at the moment
