### ISSUE TITLE
auto-syncing cloud whitelist

### ISSUE THREAD

**Issue by CosmicWebServices** [bridgevar/bridgevar-js#27]
https://scratch.mit.edu/users/jokebookservice1/#comments-25163972

**Comment by joker314** [comment]
That comment was me not understanding. The whitelist gets transmitted to the project, not the project transmitting unvalidated words to the server. Unless you were talking about the comment chain in general?

**Comment by joker314** [comment]
And isn't this about bridgevar/cloud-whitelist

**Comment by ghost** [comment]
yes

**Comment by joker314** [comment]
Shouldn't this be there then?

**Comment by ghost** [comment]
yup

**Comment by ghost** [comment]
Why'd yam close it?

**Comment by CosmicWebServices** [comment]
I think it should not be in this project
