### ISSUE TITLE
What happens when Scratch gets patched?

### ISSUE THREAD

**Issue by JordanB-1337** [bridgevar/bridgevar-js#29]
You appear to be using a security hole to modify others' cloud data.

If Scratch patches this (even though they probably won't :P) then what?

**Comment by ghost** [comment]
It's not a security hole (if you ask me).

**Comment by ghost** [comment]
If it does, we'll talk to them about a solution.

**Comment by CosmicWebServices** [comment]
It is a hidden api not a security hole

**Comment by JordanB-1337** [comment]
I don't think it's intentional.

**Comment by CosmicWebServices** [comment]
Well we had permission to do this so I bought they will patch it.

**Comment by ghost** [comment]
@CosmicWebServices ???

**Comment by CosmicWebServices** [comment]
*nm
