### ISSUE TITLE
Make it easier to add new projects

### ISSUE THREAD

**Issue by CosmicWebServices** [bridgevar/bridgevar-js#3]
Make a way that you can do something like:

`addNewBridge(num1,num2,user1,user2);`

It would add scripts to the json but we would have to make it be able to handle this in the base code.

**Comment by ghost** [comment]
hmm...  JSON editing isn't that hard...

**Comment by CosmicWebServices** [comment]
I know but can it handle it...

**Comment by CosmicWebServices** [comment]
See your code only looks at two projects alone

**Comment by CosmicWebServices** [comment]
We need to make it so it can look at as many as added on the json

**Comment by ghost** [comment]
you just need to do 

```

{
"users": [{"firstProjectId": 115557663, "secondProjectId": 115557644, "firstName": "bridgeVar", "secondName": "bridgeVar"}, {anotherobjectwiththeinfo}]
}
```

**Comment by CosmicWebServices** [comment]
I know but will the code look at those `{anotherobjectwiththeinfo}`

**Comment by ghost** [comment]
Lol yes

**Comment by CosmicWebServices** [comment]
OK

**Comment by joker314** [comment]
Just do ParsedJSON.push({data1, data2, data3, etc.})

**Comment by ghost** [comment]
yes
